"""empty message

Revision ID: 19e6695c569b
Revises: 847227d4bef6
Create Date: 2020-05-23 11:19:35.138663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e6695c569b'
down_revision = '847227d4bef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('iso_code', sa.String(length=8), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_reference')
    # ### end Alembic commands ###
