"""empty message

Revision ID: 23e54730bc25
Revises: b3e390a41af6
Create Date: 2020-05-19 11:00:29.405117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e54730bc25'
down_revision = 'b3e390a41af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_state', sa.Column('clean_date', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('us_state', 'clean_date')
    # ### end Alembic commands ###
