"""empty message

Revision ID: 26b6ea56033a
Revises: 9d9650441ccc
Create Date: 2020-05-22 17:18:07.197242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b6ea56033a'
down_revision = '9d9650441ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_data', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=64), nullable=True),
    sa.Column('to_location', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_requests')
    op.drop_table('alert_requests')
    # ### end Alembic commands ###
