"""empty message

Revision ID: 847227d4bef6
Revises: 26b6ea56033a
Create Date: 2020-05-22 17:31:09.032719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847227d4bef6'
down_revision = '26b6ea56033a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_requests', sa.Column('alert_location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_requests', 'alert_location')
    # ### end Alembic commands ###
