"""empty message

Revision ID: 9d9650441ccc
Revises: 23e54730bc25
Create Date: 2020-05-21 15:06:12.958139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9650441ccc'
down_revision = '23e54730bc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_state_name', sa.String(length=64), nullable=True),
    sa.Column('state_abbreviation', sa.String(length=2), nullable=True),
    sa.Column('state_population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('us_reference')
    # ### end Alembic commands ###
