"""empty message

Revision ID: b3e390a41af6
Revises: e8d307ccd871
Create Date: 2020-05-19 10:59:20.535401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e390a41af6'
down_revision = 'e8d307ccd871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('clean_date', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'clean_date')
    # ### end Alembic commands ###
